openapi: 3.0.0
info:
  title: Pokemon Attack API
  description: Documentation for the Attack entity
  version: 1.0.0
servers:
  - url: http://localhost:3001
    description: Local server
components:
  schemas:
    Attack:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier of the attack
        name:
          type: string
          description: Name of the attack
        description:
          type: string
          description: Description of the attack
        value:
          type: integer
          description: Damage value of the attack
      example:
        id: '1'
        name: Thunderbolt
        description: A powerful electric attack.
        value: 50
paths:
  /v1/attacks:
    get:
      summary: Get all attacks
      tags:
        - Attacks
      parameters:
        - in: query
          name: skip
          schema:
            type: integer
            default: 0
          description: Number of items to skip
        - in: query
          name: take
          schema:
            type: integer
            default: 5
          description: Number of items to take
      responses:
        '200':
          description: A list of attacks
          content:
            application/json:
              schema:
                type: object
                properties:
                  Attacks:
                    type: array
                    items:
                      $ref: '#/components/schemas/Attack'
                  totalCount:
                    type: integer
                    description: Total number of attacks
    post:
      summary: Create a new attack
      tags:
        - Attacks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Attack'
      responses:
        '200':
          description: The created attack
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Attack'
    patch:
      summary: Update an existing attack
      tags:
        - Attacks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Attack'
      responses:
        '200':
          description: The updated attack
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Attack'
  /v1/attacks/{id}:
    get:
      summary: Get an attack by ID
      tags:
        - Attacks
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the attack to retrieve
      responses:
        '200':
          description: Attack data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Attack'
        '404':
          description: Attack not found
    delete:
      summary: Delete an attack by ID
      tags:
        - Attacks
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the attack to delete
      responses:
        '202':
          description: Successfully deleted
        '404':
          description: Attack not found
