openapi: 3.0.0
info:
  title: Pokemon Attack API
  description: Documentation for the Battle feature
  version: 1.0.0
servers:
  - url: http://localhost:3001
    description: Local server
components:
  schemas:
    Battle:
      type: object
      properties:
        cardId1:
          type: string
          description: Unique identifier of the first card
        cardId2:
          type: string
          description: Unique identifier of the second card
paths:
  /v1/battle:
    post:
      summary: Battle simulation between cards
      tags:
        - Battle
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Battle'
      responses:
        '200':
          description: The result of the battle
          content:
            application/json:
              schema:
                type: boolean
        '404':
          description: Card not found
